In [1]:
import numpy as np
import random
import matplotlib.pyplot as plt
import smartscan as ss
from pathlib import Path

In [2]:
sm = ss.SmartScanGP('localhost', 54333)

In [3]:
sm.sgm4.connect()

Connecting to localhost:54333
Sending message: NDIM
Waiting for response
Received: NDIM 2

Connecting to localhost:54333
Sending message: LIMITS
Waiting for response
Received: LIMITS 0.000000,100.000000 -100.000000,0.000000

LIMITS 0.000000,100.000000 -100.000000,0.000000
Connecting to localhost:54333
Sending message: CURRENT_POS
Waiting for response
Received: CURRENT_POS LoopA:50.0 LoopB:-50.0

Connecting to localhost:54333
Sending message: FILENAME
Waiting for response
Received: FILENAME D:\Data\2023\06June\CS008\Test1_6.h5



In [4]:
sm.open()

Connecting to localhost:54333
Sending message: FILENAME
Waiting for response
Received: FILENAME D:\Data\2023\06June\CS008\Test1_6.h5



D:\Labview AJ\pycomm\smartscan\smartscan\file.py:55: UserWarning: swmr=True only affects read ('r') mode. For swmr write mode, set f.swmr_mode = True after opening the file.
  with h5py.File(self.filename, 'a', swmr=self.swmr) as f:


In [5]:
sm.file.limits

[0.0, 100.0, -100.0, 0.0]

In [6]:
sm.sgm4._limits = None
sm.sgm4.limits

Connecting to localhost:54333
Sending message: LIMITS
Waiting for response
Received: LIMITS 0.000000,100.000000 -100.000000,0.000000

LIMITS 0.000000,100.000000 -100.000000,0.000000


[(0.0, 100.0), (-100.0, 0.0)]

In [7]:
sm.update_data()

Combining same position data: 0it [00:00, ?it/s]

In [8]:
sm.values

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]])

In [15]:
sm.positions

array([[ 5.00000000e+01, -5.00000000e+01],
       [-9.99999999e+08, -9.99999999e+08]])

In [10]:
from itertools import product

In [11]:
data = np.ones(10)
positions = np.array(tuple(product(range(2),range(5))))
data,positions
positions == [0,0]


array([[ True,  True],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [False,  True],
       [False, False],
       [False, False],
       [False, False],
       [False, False]])

In [12]:
sm.sgm4.send_command('MEASURE')

Connecting to localhost:54333
Sending message: MEASURE
Waiting for response
Received: ERROR 1 badcommand



'ERROR 1 badcommand'

In [13]:
sm.sgm4.ADD_POINT(-1500.0,-1600.0)

Connecting to localhost:54333
Sending message: ADD_POINT -1500.0 -1600.0
Waiting for response
Received: ADD_POINT -999999999.000000 -999999999.000000



True

In [14]:
sm.sgm4.axes

AttributeError: 'SGM4Controller' object has no attribute 'axes'