In [2]:
import numpy as np
# import smartscan as ss

In [3]:
from typing import *
from itertools import product
def closest_point_on_grid(x: Tuple[float], axes:Sequence[Sequence[float]]) -> Tuple[int]:
    """Find the closest point in a grid to a given point"""
    grid = np.asarray(tuple(product(*axes)))
    return grid[np.linalg.norm(grid-x,axis=1).argmin()]

closest_point_on_grid((.1,.4), axes=[[-1.,0.,1.],[-1.,0.,1.]])

array([0., 0.])

In [45]:
%%time
res = ss.TCP.send_tcp_message(
    'localhost',
    port=54333,
    msg = 'MEASURE',
    buffer_size=1024*1024*8,    
)
if 'ERROR' in res:
    print(res)
else:
    vals = res.strip('\r\n').split(' ')[1:]
    n_pos = int(vals[0])
    vals = [v for v in vals if len(v)>0]
    positions = np.asarray(vals[:n_pos], dtype=float)
    data = np.asarray(vals[n_pos+1:], dtype=float)#.reshape(640,400)
    print(positions)
    print(data, data.dtype)

[ 2. 50.]
[0. 0. 0. ... 0. 0. 0.] float64
CPU times: total: 0 ns
Wall time: 23.9 ms


In [9]:
res

'MEASURE 2 50.000000 -50.000000 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.0

In [ ]:
len(res)/1024/1024

1.6818456649780273

In [ ]:
data.astype(np.float32)

array([[0.4728, 0.4079, 0.055 , ..., 0.7763, 0.9039, 0.3441],
       [0.2679, 0.4969, 0.6138, ..., 0.7193, 0.4863, 0.771 ],
       [0.0722, 0.4853, 0.8156, ..., 0.0809, 0.7345, 0.1743],
       ...,
       [0.999 , 0.363 , 0.2274, ..., 0.9044, 0.258 , 0.615 ],
       [0.8063, 0.9656, 0.2051, ..., 0.0386, 0.835 , 0.7615],
       [0.7856, 0.8068, 0.4583, ..., 0.6975, 0.9274, 0.0824]],
      dtype=float32)

In [ ]:
len(res)//1024

1750

In [ ]:
256001/640

400.0015625

In [ ]:
640 * 400 * 7 / 1024 / 1024

1.708984375

In [ ]:
def measure_over_tcp():
    res = ss.TCP.send_tcp_message(
    'localhost',
    port=12345,
    msg = 'MEASURE'
    )
    if 'ERROR' in res:
        print(res)
        raise ValueError(f'Error in tcp communication: {res}')
    else:
        positions = np.asarray(res.split(' ')[1:3], dtype=float)
        data = np.asarray(res.split(' ')[3:], dtype=float).reshape(6,4)
        print(positions)
        print(data)
    return data,positions

In [ ]:
for i in range(10):
    measure_over_tcp()

[-1730. -3104.]
[[0.51517498 0.99140576 0.12933595 0.43306862]
 [0.5616816  0.1544269  0.29778099 0.91489008]
 [0.60044032 0.53985115 0.96509491 0.93165707]
 [0.37320826 0.54552519 0.99353624 0.80496351]
 [0.96384405 0.0372523  0.37500889 0.63151213]
 [0.19563687 0.94446384 0.56647204 0.05621039]]
[-1730. -3104.]
[[0.11372239 0.02987647 0.9396698  0.10793484]
 [0.43782505 0.7728321  0.61359935 0.23454245]
 [0.18528424 0.45910508 0.79300098 0.86646979]
 [0.97825174 0.39364148 0.26532822 0.23502693]
 [0.73381883 0.64935853 0.93766035 0.10545233]
 [0.7992895  0.13238739 0.39003147 0.1773517 ]]
[-1730. -3104.]
[[0.52060673 0.63117674 0.22855945 0.23613867]
 [0.82162208 0.7258991  0.88269045 0.82020086]
 [0.60875128 0.77666523 0.05663406 0.86451377]
 [0.5813826  0.78139819 0.44430411 0.7171995 ]
 [0.45971024 0.36537614 0.45087727 0.00546101]
 [0.55138985 0.17015539 0.4130894  0.09651909]]
[-1730. -3104.]
[[0.61830836 0.17811076 0.22280154 0.3012456 ]
 [0.19976544 0.45055176 0.29027584 0.076

In [ ]:
import time
import random

In [ ]:
        # pos, data = self.measure()
        pos_str = f'{[0.2,1.5]}'.strip('[]').replace(',', '')
        data_str = ' '.join([str(v) for v in np.random.rand(6,4).ravel()])

In [ ]:
s = pos +' ' + data
positions = np.asarray(s.split(' ')[:2], dtype=float)
data = np.asarray(s.split(' ')[2:], dtype=float).reshape(6,4)


In [ ]:
positions, data

(array([0.2, 1.5]),
 array([[0.70828642, 0.65477349, 0.94329481, 0.32855083],
        [0.476565  , 0.5816438 , 0.145918  , 0.1411301 ],
        [0.22668804, 0.58254519, 0.41205948, 0.70477075],
        [0.9953232 , 0.69140445, 0.13419708, 0.93376495],
        [0.135411  , 0.50777864, 0.68012996, 0.07138841],
        [0.71975417, 0.50604963, 0.17103106, 0.15348586]]))

In [ ]:
data

'0.35659526 0.00192913 0.8911064  ... 0.61194203 0.16108009 0.25768873'

In [ ]:
[float(v) for v in s.split(' ') if len(v) > 0]

In [ ]:
' '.join([str(v) for v in np.random.rand(6,4).ravel()])

'0.6992130213117644 0.3411346706270225 0.7849291535559255 0.8016419544301998 0.09232214898042801 0.279515651599639 0.5458186012893982 0.8326442020132268 0.8886118847896641 0.35306346652728327 0.22735417237499245 0.30000685094617596 0.26015234602745296 0.9585549381165802 0.07029618258073489 0.5239753890558115 0.5455768841507009 0.10212871571788362 0.771264432119301 0.464418678793055 0.6515521764276224 0.942657961918085 0.13806489793599852 0.5084081350039057'

# comm logic

### sequential:
- connect tcp
- ask tcp parameters
- init gp
- start measurement loop
  - ask
  - send new point
  - wait for answer
  - update data

parallel:
main thread:
- connect tcp
- ask parameters
- init gp
- start measurement loop thread
- start data monitor thread
- start training thread

measurement loop thread
- if data in processed_queue
  - update data
  - ask
  - send new measurement position
  - if i in train_at: retrain
  
data monitor loop:
- listen tcp for data
- add response to raw_data_queue

data reduction thread:
- if data in raw_data_queue
- process
- add data to processed_queue
  
training thread
  ???

# async based tcp client and processor

In [7]:
import asyncio
import logging
import smartscan as ss
import numpy as np

In [8]:
host,port = 'localhost', 54333
message = 'MEASURE'
client = ss.TCP.TCPClient(host,port)
await client.connect()
await client.send_message(message)
message = await client.receive_message()
print(f'Received message: {message}')

Received message: MEASURE 2 50.000000 -50.000000 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0

In [9]:
class Logger:
    def __init__(self):
        self.info = print
        self.debug = print
        self.error = print
        self.warning = print
        self.critical = print

In [10]:
class AsyncScanManager:

    def __init__(self) -> None:
        self.tcp = ss.TCP.TCPClient('localhost', 54333, verbose=True, buffer_size=1024*1024*16)
        self._raw_data_queue = asyncio.Queue()
        self._reduced_data_queue = asyncio.Queue()
        self._gp_queue = asyncio.Queue()
        self.logger = Logger()
        # self.logger = logging.getLogger(__name__)
        # self.logger.setLevel(logging.DEBUG)
        self.logger.info('Initialized AsyncScanManager.')

    async def connect(self):
        # Connect to the tcp server
        await self.tcp.connect()
        # Start the measurement loop
        asyncio.create_task(self.measurement_loop())
        # Start the gp loop
        asyncio.create_task(self.gp_loop())
        # Start the data reduction loop
        asyncio.create_task(self.data_reduction_loop())
        self.logger.info('Started all loops.')
        
    def close(self):

        # self.tcp.close()
        self.logger.info('Closed tcp connection.')

    async def all_loops(self):
        """
        Start all the loops.
        """
        # loop_methods = [getattr(self, method)() for method in dir(self) if method.endswith('_loop')]
        # await asyncio.gather(*loop_methods)
        await asyncio.gather(
            self.gp_loop(),
            self.training_loop(),
            self.killer_loop(),
            self.reduction_loop(),
            self.fetch_data_loop(),
        )
        self.logger.info('All loops finished.')

    async def async_fetch_data(self):
        await self.tcp.connect()
        await self.tcp.send_message('MEASURE')
        return await self.tcp.receive_message()

    def fast_fetch_data(self,):
        return ss.TCP.send_tcp_message(
            'localhost',
            port=54333,
            msg = 'MEASURE',
            buffer_size=1024*1024*8,    
        )

    async def fetch_data(self):
        # message = await self.async_fetch_data()
        message = self.fast_fetch_data()
        self.logger.info(f'Received data with length {len(message)/1024/1024:.2f} MB')
        vals = message.strip('\r\n').split(' ')
        msg_code = vals[0]
        vals = [v for v in vals[1:] if len(v) >0]
        match msg_code:
            case 'ERROR':
                self.logger.warning(message)
                return message, None
            case 'NO_DATA':
                self.logger.warning(message)
                return message, None
            case 'MEASURE':
                n_pos = int(vals[0])
                pos = np.asarray(vals[1:n_pos+1], dtype=float)
                data = np.asarray(vals[n_pos+1:], dtype=float)
                # data = data.reshape(640,400)
                return pos, data
            case _:
                self.logger.warning(f'Unknown message code: {msg_code}')
                return message, None
            
    async def fetch_data_loop(self):
        """ Get data from SGM4"""
        while not self._should_stop:
            pos, data = await self.fetch_data()
            if data is not None:
                self._raw_data_queue.put_nowait((pos, data))
                self.logger.debug(f'Put data in queue: {pos}, {data}')
            else:
                await asyncio.sleep(.5)

    async def gp_loop(self):
        while not self._should_stop:
            self.logger.info('gp looping...')
            await asyncio.sleep(.7)
        
    async def reduction_loop(self):
        while not self._should_stop:
            self.logger.info('reduction looping...')
            if self._raw_data_queue.qsize() > 0:
                pos,data = await self._raw_data_queue.get()
                reduced = np.asarray([data.mean(), data.std()])
                # self.logger.info(f'adding {(pos,reduced)} to processed queue')
                self._reduced_data_queue.put_nowait((pos,reduced))
                self.logger.info(f'added {(pos,reduced)} to processed queue, currently {self._reduced_data_queue.qsize()}')
            else:
                await asyncio.sleep(.2)
    
    async def training_loop(self):
        while not self._should_stop:
            self.logger.info('training looping...')
            await asyncio.sleep(1)

    async def prediction_loop(self):
        while not self._should_stop:
            self.logger.info('prediction looping...')
            await asyncio.sleep(1)

    def kill(self):
        self.logger.info('Killing all loops.')
        self._should_stop = True

    async def start(self):
        self.logger.info('Starting all loops.')
        self._should_stop = False
        await self.all_loops()

    def stop(self):
        self.logger.info('Stopping all loops.')
        self.kill()
        self.close()
    
    async def killer_loop(self):
        await asyncio.sleep(10)
        self.logger.info('Killer loop strikes!.')
        self.stop()
       

In [11]:
tc = AsyncScanManager()
p,d = await tc.fetch_data()
print(p, d)

Initialized AsyncScanManager.
Received data with length 1.22 MB
[ 50. -50.] [0. 0. 0. ... 0. 0. 0.]


In [12]:
await tc.start()

Starting all loops.
gp looping...
training looping...
reduction looping...
Received data with length 1.22 MB
Put data in queue: [ 50. -50.], [0. 0. 0. ... 0. 0. 0.]
Received data with length 1.22 MB
Put data in queue: [ 50. -50.], [0. 0. 0. ... 0. 0. 0.]
Received data with length 1.22 MB
Put data in queue: [ 50. -50.], [0. 0. 0. ... 0. 0. 0.]
Received data with length 1.22 MB
Put data in queue: [ 50. -50.], [0. 0. 0. ... 0. 0. 0.]
Received data with length 1.22 MB
Put data in queue: [ 50. -50.], [0. 0. 0. ... 0. 0. 0.]
Received data with length 1.22 MB
Put data in queue: [ 50. -50.], [0. 0. 0. ... 0. 0. 0.]
Received data with length 1.22 MB
Put data in queue: [ 50. -50.], [0. 0. 0. ... 0. 0. 0.]
Received data with length 1.22 MB
Put data in queue: [ 50. -50.], [0. 0. 0. ... 0. 0. 0.]
Received data with length 1.22 MB
Put data in queue: [ 50. -50.], [0. 0. 0. ... 0. 0. 0.]
Received data with length 1.22 MB
Put data in queue: [ 50. -50.], [0. 0. 0. ... 0. 0. 0.]
Received data with length

In [13]:
tc._raw_data_queue.qsize(), tc._reduced_data_queue.qsize()

(0, 50)

In [18]:
await tc._reduced_data_queue.get()

(array([ 50., -50.]), array([6.37500000e-05, 8.06355604e-03]))

In [22]:
from smartscan.asyncscanner import AsyncScanManager

import logging

# init logger
logger = logging.getLogger('async_scan_manager')
logger.setLevel("DEBUG")
formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s | %(message)s')

fh = logging.FileHandler('./log.txt')
fh.setLevel('DEBUG')
fh.setFormatter(formatter)
logger.addHandler(fh)

sh = logging.StreamHandler()
sh.setLevel("DEBUG")
sh.setFormatter(formatter)
logger.addHandler(sh)

In [25]:
scan_manager = AsyncScanManager(
        host='localhost',
        port= 54333,
        logger=logger,
        train_at=[10,20,40,80,160,320],
        duration = 1000000000,
    )
p,d = await tc.fetch_data()
print(p, d)

2023-06-26 11:54:28,779 - async_scan_manager - INFO | Initialized AsyncScanManager.
2023-06-26 11:54:28,779 - async_scan_manager - INFO | Initialized AsyncScanManager.


Received data with length 1.22 MB
[ 50. -50.] [0. 0. 0. ... 0. 0. 0.]


In [26]:
await tc.start()

Starting all loops.
gp looping...
training looping...
reduction looping...
Received data with length 1.22 MB
Put data in queue: [ 50. -50.], [0. 0. 0. ... 0. 0. 0.]
Received data with length 1.22 MB
Put data in queue: [ 50. -50.], [0. 0. 0. ... 0. 0. 0.]
Received data with length 1.22 MB
Put data in queue: [ 50. -50.], [0. 0. 0. ... 0. 0. 0.]
Received data with length 1.22 MB
Put data in queue: [ 50. -50.], [0. 0. 0. ... 0. 0. 0.]
Received data with length 1.22 MB
Put data in queue: [ 50. -50.], [0. 0. 0. ... 0. 0. 0.]
Received data with length 1.22 MB
Put data in queue: [ 50. -50.], [0. 0. 0. ... 0. 0. 0.]
Received data with length 1.22 MB
Put data in queue: [ 50. -50.], [0. 0. 0. ... 0. 0. 0.]
Received data with length 1.22 MB
Put data in queue: [ 50. -50.], [0. 0. 0. ... 0. 0. 0.]
Received data with length 1.22 MB
Put data in queue: [ 50. -50.], [0. 0. 0. ... 0. 0. 0.]
Received data with length 1.22 MB
Put data in queue: [ 50. -50.], [0. 0. 0. ... 0. 0. 0.]
Received data with length