In [1]:
import numpy as np
import smartscan as ss

In [19]:
res = ss.TCP.send_tcp_message(
    'localhost',
    port=12345,
    msg = 'MEASURE',
    buffer_size=1024*1024*8,    
)
if 'ERROR' in res:
    print(res)
else:
    vals = res.split(' ')[1:]
    n_pos = int(vals[0])
    positions = np.asarray(vals[:n_pos], dtype=float)
    data = np.asarray(vals[n_pos+1:], dtype=float).reshape(640,400)
    print(positions)
    print(data, data.dtype)

[    2. -1730.]
[[0.5432 0.5827 0.9491 ... 0.6223 0.9363 0.9796]
 [0.0603 0.2987 0.9591 ... 0.0985 0.5004 0.0741]
 [0.5046 0.1297 0.8914 ... 0.4455 0.8378 0.983 ]
 ...
 [0.5718 0.2264 0.2686 ... 0.0112 0.732  0.729 ]
 [0.7118 0.4942 0.324  ... 0.6365 0.2147 0.9137]
 [0.1089 0.1363 0.2141 ... 0.8679 0.7619 0.6491]] float64


In [25]:
len(res)/1024/1024

1.6818456649780273

In [20]:
data.astype(np.float32)

array([[0.4728, 0.4079, 0.055 , ..., 0.7763, 0.9039, 0.3441],
       [0.2679, 0.4969, 0.6138, ..., 0.7193, 0.4863, 0.771 ],
       [0.0722, 0.4853, 0.8156, ..., 0.0809, 0.7345, 0.1743],
       ...,
       [0.999 , 0.363 , 0.2274, ..., 0.9044, 0.258 , 0.615 ],
       [0.8063, 0.9656, 0.2051, ..., 0.0386, 0.835 , 0.7615],
       [0.7856, 0.8068, 0.4583, ..., 0.6975, 0.9274, 0.0824]],
      dtype=float32)

In [13]:
len(res)//1024

1750

In [14]:
256001/640

400.0015625

In [11]:
640 * 400 * 7 / 1024 / 1024

1.708984375

In [150]:
def measure_over_tcp():
    res = ss.TCP.send_tcp_message(
    'localhost',
    port=12345,
    msg = 'MEASURE'
    )
    if 'ERROR' in res:
        print(res)
        raise ValueError(f'Error in tcp communication: {res}')
    else:
        positions = np.asarray(res.split(' ')[1:3], dtype=float)
        data = np.asarray(res.split(' ')[3:], dtype=float).reshape(6,4)
        print(positions)
        print(data)
    return data,positions

In [154]:
for i in range(10):
    measure_over_tcp()

[-1730. -3104.]
[[0.51517498 0.99140576 0.12933595 0.43306862]
 [0.5616816  0.1544269  0.29778099 0.91489008]
 [0.60044032 0.53985115 0.96509491 0.93165707]
 [0.37320826 0.54552519 0.99353624 0.80496351]
 [0.96384405 0.0372523  0.37500889 0.63151213]
 [0.19563687 0.94446384 0.56647204 0.05621039]]
[-1730. -3104.]
[[0.11372239 0.02987647 0.9396698  0.10793484]
 [0.43782505 0.7728321  0.61359935 0.23454245]
 [0.18528424 0.45910508 0.79300098 0.86646979]
 [0.97825174 0.39364148 0.26532822 0.23502693]
 [0.73381883 0.64935853 0.93766035 0.10545233]
 [0.7992895  0.13238739 0.39003147 0.1773517 ]]
[-1730. -3104.]
[[0.52060673 0.63117674 0.22855945 0.23613867]
 [0.82162208 0.7258991  0.88269045 0.82020086]
 [0.60875128 0.77666523 0.05663406 0.86451377]
 [0.5813826  0.78139819 0.44430411 0.7171995 ]
 [0.45971024 0.36537614 0.45087727 0.00546101]
 [0.55138985 0.17015539 0.4130894  0.09651909]]
[-1730. -3104.]
[[0.61830836 0.17811076 0.22280154 0.3012456 ]
 [0.19976544 0.45055176 0.29027584 0.076

In [135]:
import time
import random

In [62]:
        # pos, data = self.measure()
        pos_str = f'{[0.2,1.5]}'.strip('[]').replace(',', '')
        data_str = ' '.join([str(v) for v in np.random.rand(6,4).ravel()])

In [72]:
s = pos +' ' + data
positions = np.asarray(s.split(' ')[:2], dtype=float)
data = np.asarray(s.split(' ')[2:], dtype=float).reshape(6,4)


In [74]:
positions, data

(array([0.2, 1.5]),
 array([[0.70828642, 0.65477349, 0.94329481, 0.32855083],
        [0.476565  , 0.5816438 , 0.145918  , 0.1411301 ],
        [0.22668804, 0.58254519, 0.41205948, 0.70477075],
        [0.9953232 , 0.69140445, 0.13419708, 0.93376495],
        [0.135411  , 0.50777864, 0.68012996, 0.07138841],
        [0.71975417, 0.50604963, 0.17103106, 0.15348586]]))

In [55]:
data

'0.35659526 0.00192913 0.8911064  ... 0.61194203 0.16108009 0.25768873'

In [ ]:
[float(v) for v in s.split(' ') if len(v) > 0]

In [61]:
' '.join([str(v) for v in np.random.rand(6,4).ravel()])

'0.6992130213117644 0.3411346706270225 0.7849291535559255 0.8016419544301998 0.09232214898042801 0.279515651599639 0.5458186012893982 0.8326442020132268 0.8886118847896641 0.35306346652728327 0.22735417237499245 0.30000685094617596 0.26015234602745296 0.9585549381165802 0.07029618258073489 0.5239753890558115 0.5455768841507009 0.10212871571788362 0.771264432119301 0.464418678793055 0.6515521764276224 0.942657961918085 0.13806489793599852 0.5084081350039057'

# comm logic

### sequential:
- connect tcp
- ask tcp parameters
- init gp
- start measurement loop
  - ask
  - send new point
  - wait for answer
  - update data

parallel:
main thread:
- connect tcp
- ask parameters
- init gp
- start measurement loop thread
- start data monitor thread
- start training thread

measurement loop thread
- if data in processed_queue
  - update data
  - ask
  - send new measurement position
  - if i in train_at: retrain
  
data monitor loop:
- listen tcp for data
- add response to raw_data_queue

data reduction thread:
- if data in raw_data_queue
- process
- add data to processed_queue
  
training thread
  ???

# async based tcp client and processor

In [6]:
import asyncio
import logging
import smartscan as ss
import numpy as np

In [7]:
host,port = 'localhost', 12345
message = 'LIMITS'
client = ss.TCP.TCPClient(host,port)
await client.connect()
await client.send_message(message)
message = await client.receive_message()
print(f'Received message: {message}')

Received message: LIMITS -1690.0,-1770.0 -3048.0,-3160.0


In [8]:
class Logger:
    def __init__(self):
        self.info = print
        self.debug = print
        self.error = print
        self.warning = print
        self.critical = print

In [48]:
class AsyncScanManager:

    def __init__(self) -> None:
        self.tcp = ss.TCP.TCPClient('localhost', 12345, verbose=True, buffer_size=1024*1024*16)
        self._raw_data_queue = asyncio.Queue()
        self._reduced_data_queue = asyncio.Queue()
        self._gp_queue = asyncio.Queue()
        self.logger = Logger()
        # self.logger = logging.getLogger(__name__)
        # self.logger.setLevel(logging.DEBUG)
        self.logger.info('Initialized AsyncScanManager.')

    async def connect(self):
        # Connect to the tcp server
        await self.tcp.connect()
        # Start the measurement loop
        asyncio.create_task(self.measurement_loop())
        # Start the gp loop
        asyncio.create_task(self.gp_loop())
        # Start the data reduction loop
        asyncio.create_task(self.data_reduction_loop())
        self.logger.info('Started all loops.')
        
    def close(self):

        self.tcp.close()
        self.logger.info('Closed tcp connection.')

    async def all_loops(self):
        """
        Start all the loops.
        """
        loop_methods = [getattr(self, method)() for method in dir(self) if method.endswith('_loop')]
        await asyncio.gather(*loop_methods)
        self.logger.info('All loops finished.')

    async def fetch_data(self):
        await self.tcp.connect()
        await self.tcp.send_message('MEASURE')
        message = await self.tcp.receive_message()
        self.logger.info(f'Received data with length {len(message)/1024/1024:.2f} MB')
        vals = message.split(' ')
        msg_code = vals[0]
        vals = vals[1:]
        match msg_code:
            case 'ERROR':
                self.logger.warning(message)
                return message, None
            case 'NO_DATA':
                self.logger.warning(message)
                return message, None
            case 'MEASURE':
                n_pos = int(vals[0])
                pos = np.asarray(vals[1:n_pos], dtype=float)
                data = np.asarray(vals[n_pos+1:], dtype=float)
                # data = data.reshape(640,400)
                return pos, data
            case _:
                self.logger.warning(f'Unknown message code: {msg_code}')
                return message, None
            
    async def fetch_data_loop(self):
        """ Get data from SGM4"""
        while not self._should_stop:
            pos, data = await self.fetch_data()
            if pos is not None:
                self._raw_data_queue.put_nowait((pos, data))
                self.logger.debug(f'Put data in queue: {pos}, {data}')
            else:
                await asyncio.sleep(.1)
   
    async def gp_loop(self):
        while not self._should_stop:
            self.logger.info('gp looping...')
            await asyncio.sleep(.7)
        
    async def reduction_loop(self):
        while not self._should_stop:
            self.logger.info('reduction looping...')
            pos,data = await self._raw_data_queue.get()
            reduced = np.asarray([data.mean(), data.std()])
            self._reduced_data_queue.put_nowait((pos,reduced))      
            # await asyncio.sleep(.2)
    
    async def training_loop(self):
        while not self._should_stop:
            self.logger.info('training looping...')
            await asyncio.sleep(1)

    async def prediction_loop(self):
        while not self._should_stop:
            self.logger.info('prediction looping...')
            await asyncio.sleep(1)

    def kill(self):
        self.logger.info('Killing all loops.')
        self._should_stop = True

    async def start(self):
        self.logger.info('Starting all loops.')
        self._should_stop = False
        await self.all_loops()

    def stop(self):
        self.logger.info('Stopping all loops.')
        self.kill()
        self.close()
    
    async def killer_loop(self):
        await asyncio.sleep(10)
        self.logger.info('Killer loop strikes!.')
        self.stop()
       

In [50]:
tc = AsyncScanManager()
p,d = await tc.fetch_data()
print(p, d)

Initialized AsyncScanManager.
Received data with length 0.25 MB
[-1730.] [0.3851 0.2868 0.7574 ... 0.5644 0.5847 0.998 ]


In [51]:
await tc.start()

Starting all loops.
gp looping...
prediction looping...
reduction looping...
training looping...
gp looping...
prediction looping...
training looping...
gp looping...
prediction looping...
training looping...
Received data with length 0.25 MB
Put data in queue: [-1730.], [0.8157 0.3759 0.7916 ... 0.1621 0.963  0.358 ]
reduction looping...
gp looping...
gp looping...
prediction looping...
training looping...
gp looping...
Received data with length 0.25 MB
Put data in queue: [-1730.], [0.787  0.1241 0.9403 ... 0.3345 0.8313 0.493 ]
reduction looping...
prediction looping...
training looping...
gp looping...
gp looping...
prediction looping...
training looping...
gp looping...
Received data with length 0.25 MB
Put data in queue: [-1730.], [0.0118 0.1597 0.7545 ... 0.3462 0.2326 0.    ]
reduction looping...
prediction looping...
training looping...
gp looping...
prediction looping...
training looping...
gp looping...
Received data with length 0.25 MB


ValueError: could not convert string to float: ''

gp looping...
training looping...
prediction looping...
gp looping...
training looping...
prediction looping...
gp looping...
gp looping...
Killer loop strikes!.
Stopping all loops.
Killing all loops.
Closed tcp connection.


In [37]:
tc._raw_data_queue.qsize(), tc._reduced_data_queue.qsize()

(1, 0)